#!/bin/bash

NAME=delete_remote
ARGS_ORIG=$@
DST_HOST=$(echo $1 | cut -d':' -f 1)

if [ -z "${ONE_LOCATION}" ]; then
   ONE_LOCATION=/var/lib/one
fi

. $ONE_LOCATION/remotes/scripts_common.sh

log "Calling $NAME"
ssh_exec_and_log $DST_HOST \
                "$ONE_LOCATION/remotes/tm/ipfs/$NAME $ARGS_ORIG" \
                "Error calling $NAME"

exit 0
